### ISSUE TITLE
add incoming questions to todo-list

### ISSUE THREAD

**Issue by Monjola** [dothemath-se/dothemath-app-frontend#3]
When a student sends the first message of a question the bot should send
"<@U011XHE7NP5> add" to the slack thread. This message should not be sent to the chat on the web.

**Comment by memark** [comment]
What does this cryptic code mean?

**Comment by Monjola** [comment]
I'm in the process of trying out an app called @Reviewed to solve the problem of student questions going unanswered by creating a list of ongoing questions. (tryreviewed.com) It basically does what we want to be able to do but has some limitations.
**capability**

- You can write “@Reviewed add” as a response in a thread to add a task to a todo list. This I think would be done automatically on all incoming messages from the web chat of our dothemathbot.

- You can bring up all open questions in all channels by visiting the app's "website" (see image)

**Limitations**

- Cannot use “@Reviewed add” on message from bots.

- Each time a new task is added, @Reviewed sends a message to the channel that the task is in (and thus spammes the channel).

- _To mark a task as completed, you must go back to the page in the image and look up the task again and then mark it as done._ The developer of @Reviewed has taken care of this one now. You can now write @Reviewed done

I have been in contact with the developer of @Reviewed and he has said that he will solve these points above, if he does then I think we could use it together with our bot.
What we would need to do then is get the bot to automatically write “@Reviewed add” in their thread when a new question is started. Ideally, the student who sits on the website would not have to see this message so they will not be confused.
![image](https://user-images.githubusercontent.com/22137237/80892561-66d97b00-8ccb-11ea-882e-0000e4c045f5.png)

**Comment by Monjola** [comment]
<@U011XHE7NP5> is the User Id of the @Reviewed bot
